#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e


echo "Building the Next.js app..."
npm run build

# Prompt for a commit message
read -p "Enter commit message: " commit_message
read -p "Which branch?: " branch

if [ -z "$commit_message" ]; then
  echo "Commit message cannot be empty. Exiting."
  exit 1
fi

git add .
git commit -m "$commit_message"

echo "Pushing changes to the $branch branch..."
git push origin $branch

echo " Build and push completed successfully!"
echo ""
